flight_planner 1st-Iteration finish
norisimons/FlightPlanner.Web pull request #1
Opened 2021-09-20 22:16 UTC by norisimons

2021-09-22 18:33 UTC, ausmoons requested changes

2021-09-22 18:33 UTC, ausmoons commented on Controllers/TestingController.cs
>  {
Testi iziet, bet šis nav labs PR un tev ir lieku usingi projektā

2021-09-23 19:43 UTC, ausmoons requested changes

2021-09-23 19:43 UTC, ausmoons commented on DbContext/FlightPlannerDbContext.cs
> +{
Pirmais PR nav ar db

2021-09-23 20:35 UTC, norisimons commented on DbContext/FlightPlannerDbContext.cs
> +{
Main ir ar 1.iterāciju, 
brančs(2st Iteration) ir  ar 2.iterāciju(PR)

2021-09-26 19:28 UTC, ausmoons commented on DbContext/FlightPlannerDbContext.cs
> +{
2nd*

2021-09-26 19:28 UTC, ausmoons approved these changes

2021-09-26 20:44 UTC, merged